import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import Image from 'next/image';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
    return (
        <html lang="en">
            <body className={inter.className}>
                <nav>
                    <a href="/">
                        <Image src="/assets/images/about-me-icon.png" alt={''} />
                    </a>
                    <ul>
                        <li>
                            <a href="/about-me">
                                ABOUT ME <span></span>
                            </a>
                        </li>
                        <li>
                            <a href="/projects">
                                WORK <span></span>
                            </a>
                        </li>
                        <li>
                            <a href="/assets/files/resume.pdf" target="_blank">
                                RESUME <span></span>
                            </a>
                        </li>
                        <li>
                            <a href="/contact">
                                CONTACT <span></span>
                            </a>
                        </li>
                    </ul>
                </nav>
                <main>
                    <div>{children}</div>
                </main>
                <footer></footer>
            </body>
        </html>
    );
}
